version: '3'

services:
  ml_model:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8888:8888"  # For Jupyter Notebook
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/train.py"]  # Default command

  analyze:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/analyze.py"]

  predict:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/predict.py"]
